{{- if .Values.service.enabled -}}
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceExport
metadata:
  labels:
    app: {{ include "starter-kit.fullname" . }}
  name: {{ include "starter-kit.fullname" . }}
{{- end -}}